# -*- coding: utf-8 -*-
"""
Created on Wed Mar 12 19:04:07 2025

@author: Ele_p
"""

"""
Multichannel Film Dosimetry Calibration and Analysis
This tutorial demonstrates the complete workflow for multichannel calibration,
from loading calibration data to generating and saving dose maps. 
The multichannel approach combines information from all three color channels,
resulting in more accurate dose measurements especially in higher dose regions.
"""

from Calibration_EBT3 import ProcessingMode
from Calibration_EBT3.multi_calibration import MultiChannelCalibration
from Calibration_EBT3.single_channel_calibration import SingleChannelCalibration
from skimage.io import imread
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, TiffImagePlugin
import os

tutorial_dir = os.path.dirname(os.path.abspath(__file__))
data_file_red = os.path.join(tutorial_dir, "example", "Channel_red_DvsPV.csv")
data_file_green = os.path.join(tutorial_dir, "example", "Channel_green_DvsPV.csv")
data_file_blue = os.path.join(tutorial_dir, "example", "Channel_blue_DvsPV.csv")

# Load calibration data
df_red = pd.read_csv(data_file_red)
df_green = pd.read_csv(data_file_green)
df_blue = pd.read_csv(data_file_blue)

# Extract the data
x_data_red = df_red.iloc[:, 1].astype(float)    # Pixel Value/netOD
y_data_red = df_red.iloc[:, 0].astype(float)/100  # Dose (converting to Gy if necessary)

x_data_green = df_green.iloc[:, 1].astype(float)  # Pixel Value/netOD
y_data_green = df_green.iloc[:, 0].astype(float)/100  # Dose

x_data_blue = df_blue.iloc[:, 1].astype(float)  # Pixel Value/netOD
y_data_blue = df_blue.iloc[:, 0].astype(float)/100  # Dose

# Create data tuples for calibration
blue_data = (x_data_blue, y_data_blue)
red_data = (x_data_red, y_data_red)
green_data = (x_data_green, y_data_green)

# Create the multichannel calibration instance
multi_calibration = MultiChannelCalibration()

# Calibrate all channels
# You can choose different processing modes:
# ProcessingMode.PV, ProcessingMode.NET_OD, etc.
calibration_results, *weights = multi_calibration.calibrate_channels(
    red_data, green_data, blue_data, mode=ProcessingMode.PV)
#%%
# Print calibration results
print("Calibration Results:")
print(f"Red Channel Weight: {weights[0][0]:.4f}")
print(f"Green Channel Weight: {weights[0][1]:.4f}")
print(f"Blue Channel Weight: {weights[0][2]:.4f}")

#%%
# Load film images for analysis
image_red = os.path.join(tutorial_dir, "example", "CR-image.tif")
data_file_green = os.path.join(tutorial_dir, "example", "CG-image.tif")
data_file_blue = os.path.join(tutorial_dir, "example", "CB-image.tif")

image_red = imread(image_red)
image_green = imread(data_file_green)
image_blue = imread(data_file_blue)

# Calculate the combined dose using all channels
dose_combined, dose_gy_r, dose_gy_g, dose_gy_b = multi_calibration.calculate_combined_dose(
    image_red, image_green, image_blue, mode=ProcessingMode.PV)

# Calculate statistics
mean_dose_gy = np.mean(dose_combined)
median_dose_gy = np.median(dose_combined)
max_dose_gy = np.max(dose_combined)

# Visualize the dose map
plt.figure(figsize=(10, 8))
plt.imshow(dose_combined, cmap=plt.cm.bone)
plt.colorbar(label='Dose (Gy)')
plt.title('Dose Map - MultiChannel Calibration')
plt.show()

# Print statistics
print('Mean dose (Gy):', mean_dose_gy)
print('Median dose (Gy):', median_dose_gy)
print('Maximum dose (Gy):', max_dose_gy)
print('Dose map shape:', np.shape(dose_combined))

# Convert the dose map to an image
image = Image.fromarray(dose_combined)

# Add metadata
metadata = TiffImagePlugin.ImageFileDirectory_v2()
metadata[256] = dose_combined.shape[1]  # Image width
metadata[257] = dose_combined.shape[0]  # Image height
metadata[282] = (72)                 # X resolution (72 DPI)
metadata[283] = (72)                 # Y resolution (72 DPI)
metadata[305] = "Generated by Python"   # Software

# Create output directory if it doesn't exist

os.makedirs("output", exist_ok=True)

# Save the TIFF file with metadata
output_file = "output/dose_map_multichannel.tiff"
image.save(output_file, tiffinfo=metadata)

print(f"TIFF image saved as {output_file} with metadata.")